### ISSUE TITLE
Multiple questions

### ISSUE THREAD

**Issue by enepomnyaschih** [madisoft/s3-pit-restore#27]
I'm trying to learn s3-pit-restore as a restoration tool and I have a lot of questions the official documentation doesn't answer to.

I don't quite understand how -p option works. I have an S3 bucket with several folders. Each of these folders contains a backup. For example, "backup" folder contains a backup of /var/ftp folder. How am I supposed to run s3-pit-restore to restore from this backup? If I run

    s3-pit-restore -b mybucket -p backup -d /var/ftp -t "01-03-2019 12:54:00 +0"

It restores everything into /var/ftp/backup instead of /var/ftp. Why is it implemented this way and how can I deal with it? Am I supposed to maintain equal folder names locally and remotely?

Is there an option to delete the local files, such as --delete for "aws s3 sync"? It doesn't delete the files even if S3 contains an explicit deletion marker for a file.

What is the proper way to stop the application? It requires about 10 Ctrl+C calls to completely stop everything, and I suspect that this is a big stress for the application.

Is there a way to change the timestamp format? Current format (mm-dd-yyyy) is common only in USA and nowhere else. For the foreigners, it makes their brain explode and there is a serious danger for an operator to specify an incorrect recovery date, which may result in massive spoiling of a local folder.

Is there a way to preserve file modification dates if current version is equal to the remote one content-wise? This is minor, but still annoying.

Is there a way to make the output more coincise? Look at "aws s3 sync" - it just tells you the changes that have been made, and no garbage.

In general, it would be perfect if s3-pit-restore looked as similar to "aws s3 sync" as possible, just with point-in-time recovery option.

**Comment by angeloc** [comment]
> ```
> s3-pit-restore -b mybucket -p backup -d /var/ftp -t "01-03-2019 12:54:00 +0"
> ```
> 
> It restores everything into /var/ftp/backup instead of /var/ftp. Why is it implemented this way and how can I deal with it? Am I supposed to maintain equal folder names locally and remotely?

Why it should behave differently? -d is used to specify the __destination__ folder.

> Is there an option to delete the local files, such as --delete for "aws s3 sync"? It doesn't delete the files even if S3 contains an explicit deletion marker for a file.

It's a restore tool, not a synchronization tool.

> What is the proper way to stop the application? It requires about 10 Ctrl+C calls to completely stop everything, and I suspect that this is a big stress for the application.

You are doing it wrong. CRTL+C should be pressed only once and you should wait the process exits gracefully after completing the running downloads. Force killing the application is not good.

> Is there a way to change the timestamp format? Current format (mm-dd-yyyy) is common only in USA and nowhere else. For the foreigners, it makes their brain explode and there is a serious danger for an operator to specify an incorrect recovery date, which may result in massive spoiling of a local folder.

Timestamp is a timestamp. If you use the timestamp for US date and time it's your choice. You can use any of the international timestamp format here. BTW if you use the timpestamp from the webgui as suggested in the documentation you are choosing the right timestamp for sure.

> Is there a way to preserve file modification dates if current version is equal to the remote one content-wise? This is minor, but still annoying.

This is not a synchronization tool.

> Is there a way to make the output more coincise? Look at "aws s3 sync" - it just tells you the changes that have been made, and no garbage.

This is a nonsense question. The output you see is the output from the application. If you don't like it and you propose something better, please do a patch.

> In general, it would be perfect if s3-pit-restore looked as similar to "aws s3 sync" as possible, just with point-in-time recovery option.

You are free to contribute to the code or add the point-in-time recovery option to aws s3 sync!

**Comment by enepomnyaschih** [comment]
Thank you for your answers.
