### ISSUE TITLE
Restore command set S3 versions

### ISSUE THREAD

**Issue by ffelipek07** [madisoft/s3-pit-restore#29]
Good Morning
I need help, I need to restore all the contents of a bucket to a specific s3 version, or a specific date for example. 
I would like to restore all files before this date for example

s3-pit-restore -b orgin -d destination  -f "09-03-2019 23:59:50 -3"

**Comment by angeloc** [comment]
Hi @ffelipek07,

Please have a look to the documentation! You can find there all the info you need.
