### ISSUE TITLE
S3 errors being silently swallowed

### ISSUE THREAD

**Issue by james-masson** [madisoft/s3-pit-restore#6]
When this tool is used in a bucket with S3 encryption, downloads appear to succeed, but in fact fail silently.

Setting ```aws configure set s3.signature_version s3v4``` fixes the problem.

With the AWS official S3 command line tools, this failure is handled properly.

**Comment by angeloc** [comment]
@james-masson : Could you provide an example to reproduce the problem? s3-pit-restore uses the same underlying python-boto of the aws cli, so the behavior should be the same.

Thanks!

**Comment by james-masson** [comment]
behaviour with aws s3 sync 

```
[james-masson@server ~]$ aws s3 sync s3://bucket/folder/ ./
download failed: s3:/bucket/folder/folder1/folder1/_3mju.fdx to stuff/_3mju.fdx An error occurred (InvalidArgument) when calling the GetObject operation: Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4. You can enable AWS Signature Version 4 by running the command: 
aws configure set s3.signature_version s3v4
```
No files are downloaded


behaviour with s3-pit-restore

```
[james-masson@c6dev-fraud-solr01 ~]$ s3-pit-restore  -b bucket -p folder/ -d ./
folder/file1
folder/file2
folder/file3
```

No files are downloaded, but no errors are presented either.

**Comment by james-masson** [comment]
s3-pit-restore (0.7)

**Comment by james-masson** [comment]
Providing a full reproducible case is difficult. I'd have to provide you a bucket with the correct crypto policy, and ec2 instance with API access to the encryption key. Which would mean a whole new AWS account just for this.

**Comment by angeloc** [comment]
@james-masson : No problem for the reproducibility, I will try to reprodice by myself.

Could you send a debug output using the `--debug` flag?

Thanks!

**Comment by james-masson** [comment]
There's no change in output with `--debug`

exit code is 0 - file just doesn't exist.

As soon as I set `aws configure set s3.signature_version s3v4` - `s3-pit-restore` works perfectly.

**Comment by angeloc** [comment]
> There's no change in output with --debug

That's strange, another thing to investigate!

> As soon as I set aws configure set s3.signature_version s3v4 - s3-pit-restore works perfectly.

Ok, but it do not fails silently. As soon as I can reproduce the setup, I'll update this issue.

Thanks!

**Comment by angeloc** [comment]
@james-masson : Could you try the latest version from git? It should show you a detailed error message now if the file cannot be downloaded for whatever reason
