### ISSUE TITLE
DeleteMarkers are not processed

### ISSUE THREAD

**Issue by timor-raiman** [madisoft/s3-pit-restore#8]
Consider the case where an object is created between from_timestamp and timestamp (and would thus be restored) and then is deleted also before timestamp.
Expected behavior is that it would not be restored into the point-in-time snapshot.

By checking the code, it would appear that tool will ignore the DeleteMarker and erroneously restore the deleted object.

**Comment by grajeshwaran** [comment]
I am having the same issue as well. When a time range is provided for restore, the files which were deleted during that range are also restored.
Any solution ?

**Comment by timor-raiman** [comment]
This should be resolved in my fork (and the above pull request, to which madisoft did not respond...)

**Comment by grajeshwaran** [comment]
Thanks  @timor-raiman will check it.
